title:            Audrey's Portfolio
description:      A jekyll theme. Because I scribble.
url:              # Site url.
signoff:          Audrey
disqus_shortname: # disqus comment thread for post header options. ( leave blank if unwanted. )
facebook_appid:   # appid for like button, remove from /_includes/share.html if unwanted.
google_analytics: # set tracking, remove from /javascripts/basic.js if unwanted.

links:
  - name:         About
    url:          /about
  - name:         Resume
    url:          /resume
  - name:         Email
    url:          mailto:awyshi@gmail.com
    external:     true
  - name:         GitHub
    url:          http://github.com/audreyshi
    external:     true
highlighter:      pygments
permalink:        pretty
markdown:         redcarpet
redcarpet:
  extensions:
    - smart
